"""create payment cancel table

Revision ID: 01e8e2948ec3
Revises: bade3d932513
Create Date: 2025-11-02 11:12:35.665577

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "01e8e2948ec3"
down_revision: Union[str, Sequence[str], None] = "bade3d932513"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_cancel",
        sa.Column(
            "payment_cancel_id", sa.BigInteger(), autoincrement=True, nullable=False
        ),
        sa.Column("payment_id", sa.BigInteger(), nullable=False),
        sa.Column("member_id", sa.BigInteger(), nullable=False),
        sa.Column("requested_at", sa.DateTime(), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.Column("is_canceled", sa.Boolean(), nullable=False),
        sa.Column("cancel_reason", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["member.member_id"],
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payment.payment_id"],
        ),
        sa.PrimaryKeyConstraint("payment_cancel_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payment_cancel")
    # ### end Alembic commands ###
