"""create order_product table (#2)

Revision ID: 2b45ef099232
Revises: 06113c2fd337
Create Date: 2025-11-01 22:45:28.458326

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2b45ef099232"
down_revision: Union[str, Sequence[str], None] = "06113c2fd337"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_product",
        sa.Column(
            "order_product_id", sa.BigInteger(), autoincrement=True, nullable=False
        ),
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("order_product_price", sa.Integer(), nullable=False),
        sa.Column("order_product_quantity", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.order_id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.product_id"],
        ),
        sa.PrimaryKeyConstraint("order_product_id"),
    )
    op.alter_column(
        "product", "deleted_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "product", "deleted_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.drop_table("order_product")
    # ### end Alembic commands ###
