"""create order status table

Revision ID: 6cfba00c6d4d
Revises: 2b45ef099232
Create Date: 2025-11-02 09:40:23.520654

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6cfba00c6d4d"
down_revision: Union[str, Sequence[str], None] = "2b45ef099232"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_status",
        sa.Column(
            "order_status_id", sa.BigInteger(), autoincrement=True, nullable=False
        ),
        sa.Column("order_status_category", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("order_status_id"),
    )
    op.add_column(
        "orders", sa.Column("order_status_id", sa.BigInteger(), nullable=False)
    )
    op.create_foreign_key(
        None, "orders", "order_status", ["order_status_id"], ["order_status_id"]
    )
    op.drop_column("orders", "order_status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column(
            "order_status", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_column("orders", "order_status_id")
    op.drop_table("order_status")
    # ### end Alembic commands ###
