"""create points history table

Revision ID: 77fe34722410
Revises: 7f1f1db3abbe
Create Date: 2025-11-02 10:45:44.133900

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "77fe34722410"
down_revision: Union[str, Sequence[str], None] = "7f1f1db3abbe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "points_history",
        sa.Column(
            "points_history_id", sa.BigInteger(), autoincrement=True, nullable=False
        ),
        sa.Column("member_id", sa.BigInteger(), nullable=False),
        sa.Column("previous_points_balance", sa.Integer(), nullable=False),
        sa.Column("changed_amount", sa.Integer(), nullable=False),
        sa.Column("current_points_balance", sa.Integer(), nullable=False),
        sa.Column("changed_reason", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["member.member_id"],
        ),
        sa.PrimaryKeyConstraint("points_history_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("points_history")
    # ### end Alembic commands ###
