"""create member coupon history table

Revision ID: 7f1f1db3abbe
Revises: c9d10b51db7c
Create Date: 2025-11-02 10:38:43.986011

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7f1f1db3abbe"
down_revision: Union[str, Sequence[str], None] = "c9d10b51db7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "member_coupon_history",
        sa.Column(
            "member_coupon_history_id",
            sa.BigInteger(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("member_coupon_id", sa.BigInteger(), nullable=False),
        sa.Column("previous_coupon_status", sa.String(length=50), nullable=True),
        sa.Column("current_coupon_status", sa.String(length=50), nullable=False),
        sa.Column("applied_discount_rate", sa.Integer(), nullable=False),
        sa.Column("changed_reason", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_coupon_id"],
            ["member_coupon.member_coupon_id"],
        ),
        sa.PrimaryKeyConstraint("member_coupon_history_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("member_coupon_history")
    # ### end Alembic commands ###
