"""create product table

Revision ID: 82c6744561a7
Revises: 95df47f4e8e4
Create Date: 2025-11-01 17:45:31.130776

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "82c6744561a7"
down_revision: Union[str, Sequence[str], None] = "95df47f4e8e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("product_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("product_name", sa.String(length=100), nullable=False),
        sa.Column("seller", sa.String(length=50), nullable=False),
        sa.Column("origin", sa.String(length=50), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("product_status", sa.String(length=50), nullable=False),
        sa.Column("product_price", sa.Integer(), nullable=False),
        sa.Column("stock_quantity", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("product_id"),
        sa.UniqueConstraint(
            "product_name", "seller", "origin", name="uq_product_seller_origin"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product")
    # ### end Alembic commands ###
