"""create member table

Revision ID: 95df47f4e8e4
Revises:
Create Date: 2025-11-01 12:55:20.497851

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "95df47f4e8e4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "member",
        sa.Column("member_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("login_id", sa.String(length=50), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("password_check_question", sa.String(length=100), nullable=False),
        sa.Column("password_check_answer", sa.String(length=255), nullable=False),
        sa.Column("member_name", sa.String(length=20), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("is_email_agreed", sa.Boolean(), nullable=False),
        sa.Column(
            "gender", sa.Enum("MALE", "FEMALE", name="membergender"), nullable=False
        ),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column("points_balance", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("member_id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("login_id"),
        sa.UniqueConstraint("phone_number"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("member")
    # ### end Alembic commands ###
