"""create shipping and shipping status tables

Revision ID: 991a8a0f47cf
Revises: a218b49d142d
Create Date: 2025-11-02 11:26:16.142438

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "991a8a0f47cf"
down_revision: Union[str, Sequence[str], None] = "a218b49d142d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shipping_status",
        sa.Column(
            "shipping_status_id", sa.BigInteger(), autoincrement=True, nullable=False
        ),
        sa.Column("shipping_status_category", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("shipping_status_id"),
    )
    op.create_table(
        "shipping",
        sa.Column("shipping_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column("shipping_status_id", sa.BigInteger(), nullable=False),
        sa.Column("shipping_address", sa.String(length=100), nullable=False),
        sa.Column("tracking_number", sa.String(length=50), nullable=False),
        sa.Column("shipped_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.order_id"],
        ),
        sa.ForeignKeyConstraint(
            ["shipping_status_id"],
            ["shipping_status.shipping_status_id"],
        ),
        sa.PrimaryKeyConstraint("shipping_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shipping")
    op.drop_table("shipping_status")
    # ### end Alembic commands ###
