"""create payment status table

Revision ID: a218b49d142d
Revises: 01e8e2948ec3
Create Date: 2025-11-02 11:15:55.316303

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a218b49d142d"
down_revision: Union[str, Sequence[str], None] = "01e8e2948ec3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_status",
        sa.Column(
            "payment_status_id", sa.BigInteger(), autoincrement=True, nullable=False
        ),
        sa.Column("payment_status_category", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("payment_status_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payment_status")
    # ### end Alembic commands ###
