"""create member coupon and member coupon status tables

Revision ID: c9d10b51db7c
Revises: 458d1b722a7c
Create Date: 2025-11-02 10:24:46.477747

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c9d10b51db7c"
down_revision: Union[str, Sequence[str], None] = "458d1b722a7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "member_coupon_status",
        sa.Column(
            "member_coupon_status_id",
            sa.BigInteger(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("member_coupon_status_id"),
    )
    op.create_table(
        "member_coupon",
        sa.Column(
            "member_coupon_id", sa.BigInteger(), autoincrement=True, nullable=False
        ),
        sa.Column("member_id", sa.BigInteger(), nullable=False),
        sa.Column("coupon_id", sa.BigInteger(), nullable=False),
        sa.Column("member_coupon_status_id", sa.BigInteger(), nullable=False),
        sa.Column("expired_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["coupon_id"],
            ["coupon.coupon_id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_coupon_status_id"],
            ["member_coupon_status.member_coupon_status_id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["member.member_id"],
        ),
        sa.PrimaryKeyConstraint("member_coupon_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("member_coupon")
    op.drop_table("member_coupon_status")
    # ### end Alembic commands ###
