"""add index for pagination on product table

Revision ID: e4b02e6e49a1
Revises: 65f017e3af56
Create Date: 2025-11-15 11:29:21.692798

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "e4b02e6e49a1"
down_revision: Union[str, Sequence[str], None] = "65f017e3af56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_product_category_created_pid",
        "product",
        ["is_deleted", "product_status", "category", "created_at", "product_id"],
        unique=False,
    )
    op.create_index(
        "idx_product_created_pid",
        "product",
        ["is_deleted", "product_status", "created_at", "product_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_product_created_pid", table_name="product")
    op.drop_index("idx_product_category_created_pid", table_name="product")
    # ### end Alembic commands ###
